nordeck/matrix-widget-toolkit

- README.md
- example-widget-mui/README.md
- example-widget-mui/package.json
- example-widget-semantic-ui/README.md
- example-widget-semantic-ui/package.json
- package.json
- yarn.lock
This also removes localtunnel from the setup. You can still install localtunnel manually, there is no need to deliver it with the project.
> Improve documentation on running the widget locally

- .eslintrc.js
- scripts/license-header.txt
This makes us ready for 2023 😉 
> Improve notice header to allow other years and names

- .changeset/shiny-poems-cough.md
- packages/mui/src/components/MuiThemeProvider/MuiThemeProvider.tsx
> Check base language instead of the full string

- .changeset/mighty-bobcats-drum.md
- packages/api/src/api/WidgetApiImpl.ts
> Don't return `null` values for the pagination token of the relations endpoint

- README.md
> PB-3115 fix-adr-link

- .github/dependabot.yml
- .github/workflows/ci.yml
- .prettierignore
- charts/example-widget-mui/.helmignore
- charts/example-widget-mui/Chart.yaml
- charts/example-widget-mui/templates/NOTES.txt
- charts/example-widget-mui/templates/_helpers.tpl
- charts/example-widget-mui/templates/deployment.yaml
- charts/example-widget-mui/templates/hpa.yaml
- charts/example-widget-mui/templates/ingress.yaml
- charts/example-widget-mui/templates/service.yaml
- charts/example-widget-mui/templates/serviceaccount.yaml
- charts/example-widget-mui/templates/tests/test-connection.yaml
- charts/example-widget-mui/values.yaml
- example-widget-mui/Dockerfile
> Create a helm chart for the mui example widget

- .changeset/happy-moons-attack.md
- package.json
- packages/api/api-report.md
- packages/api/src/api/WidgetApiImpl.test.ts
- packages/api/src/api/WidgetApiImpl.ts
- packages/api/src/api/index.ts
- packages/api/src/api/types.ts
- packages/testing/api-report.md
- packages/testing/src/api/mockWidgetApi.test.ts
- packages/testing/src/api/mockWidgetApi.ts
- yarn.lock
> Implement sending and receiving of to device messages

- .github/workflows/ci.yml
> Add version comment to action

- .changeset/gold-ears-help.md
- .changeset/metal-bees-shop.md
- example-widget-mui/src/ThemePage/ThemePage.tsx
- packages/mui/src/components/MuiThemeProvider/theme.ts
- packages/testing/api-report.md
- packages/testing/src/api/mockWidgetApi.ts
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
> Set a custom border color for tables

- example-widget-mui/src/ThemePage/ThemePage.tsx
> Fix the syntax of the table example

- .changeset/pink-hotels-boil.md
- example-widget-mui/src/ThemePage/ThemePage.tsx
- packages/mui/api-report.md
- packages/mui/src/components/ElementAvatar/ElementAvatar.tsx
> Forward `ref` in `<ElementAvatar>`

- .github/workflows/ci.yml
- example-widget-mui/README.md
The widget is available at https://example-widget-mui.widgets.demo.nordeck.io/.
> Deploy the MUI example widget to a demo cluster

- packages/api/README.md
I fixed a small typo in the README.
> Fix typo in README.md

- .github/dependabot.yml
Uses the ["group" feature of Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) to simplify the updates of Material UI.
> Group dependabot PRs for Material UI

- .changeset/dull-cougars-do.md
- .github/workflows/ci.yml
- README.md
- example-widget-mui/package.json
- example-widget-semantic-ui/package.json
- package.json
- packages/api/package.json
- packages/mui/package.json
- packages/react/package.json
- packages/semantic-ui/package.json
- packages/testing/package.json
- yarn.lock
> Upgrade to Node.js 20

- .changeset/honest-islands-invite.md
- packages/mui/src/components/MuiThemeProvider/EmotionCacheProvider.tsx
> Add prepend to emotion cache provider

- .husky/pre-commit
- package.json
- yarn.lock
> Update husky, nth-check, postcss

- yarn.lock
> Update postcss dependency

- eslint.config.mjs
- package.json
- yarn.lock
> Add eslint-plugin-testing-library

- .changeset/gold-penguins-approve.md
- .changeset/lovely-seas-cheer.md
- example-widget-mui/src/ImagePage/ImageListView.tsx
- packages/mui/package.json
- packages/react/package.json
- packages/testing/package.json
- packages/testing/src/api/mockWidgetApi.test.ts
- `testing` adds support for mocking `downloadFile` method in `MockedWidgetApi`
- `mui` bumps to MUI v6
- `react` bump for assorted dependencies
> Version bumps for 'mui', 'react' and 'testing' packages

- README.md
> Added notable projects section to the README

- README.md
> Add matrix room badge

- README.md
> Replaces dynamic with static badge

- eslint.config.mjs
- example-widget-mui/src/ImagePage/Image.tsx
- package.json
- yarn.lock
> Add eslint-plugin-react-hooks

- package.json
> Remove deprecated husky install command

- scripts/publishAllPackages.js
> fix release pipeline

- packages/testing/README.md
> Replace jest with vitest

- .github/renovate.json
> improve labeling in renovate by adding new engines rule

- packages/mui/package.json
- packages/react/package.json
This is needed for the [companion neoboard PR](https://github.com/nordeck/matrix-neoboard/pull/612) which makes use of yarn link for easier development
> Set up package dependencies up in a way that yarn link works

- .changeset/config.json
> Update changeset config to not ignore private packages

- .github/renovate.json
- .prettierignore
> Limit Renovate React updates to version 18

- README.md
- containers/widget-server/package.json
- example-widget-mui/package.json
- package.json
- packages/api/package.json
- packages/mui/package.json
- packages/react/package.json
- packages/testing/package.json
Similar to https://github.com/nordeck/matrix-neoboard/pull/678
> Add clean scripts

- containers/widget-server/README.md
> Add info about Strict-Transport-Security header

- .github/workflows/ci.yml
> Add the latest tag when pushing to main

- .github/k8s_config.yaml
- .github/workflows/ci.yml
Does apply the helm chart to see if it is working.
> Add helm lint

- .changeset/soft-masks-sneeze.md
- containers/widget-server/README.md
- containers/widget-server/files/default.conf
> Adjust widgets HTTP cache control

- .changeset/unlucky-carrots-shout.md
- packages/api/api-report.api.md
- packages/api/package.json
- packages/api/src/api/WidgetApiImpl.test.ts
- packages/api/src/api/WidgetApiImpl.ts
- packages/api/src/api/extras/events.test.ts
- packages/api/src/api/extras/events.ts
- packages/api/src/api/extras/index.ts
- yarn.lock
Before the change it was assumed, that events coming down the Widget API are always correct. This commit adds Joi schemas and validation functions for room and state events and to device messages.
> Add strict(er) Matrix event validation

- .changeset/poor-doodles-change.md
> Adding testing package changeset for deps update

- .github/renovate.json
Just only allowing patch versions should already do the same
Fixes #926
> Fix renovate.json

- .changeset/great-pets-add.md
- example-widget-mui/package.json
- package.json
- packages/api/package.json
- packages/mui/package.json
- packages/react/package.json
- packages/testing/package.json
- packages/testing/src/api/mockWidgetApi.test.ts
- vitest.config.ts
- yarn.lock
> Upgrade vitest to newest version

- .github/renovate.json5
> Renovate: Extending groups is not allowed

- .github/renovate.json5
> Increase the pr hourly limit since we only run once a week and it would only create 2 PRs per week otherwise

- .changeset/slimy-ants-grin.md
- packages/api/api-report.api.md
- packages/api/src/api/extras/events.test.ts
- packages/api/src/api/extras/events.ts
> Add optional type to the content of m.room.create
