.changeset/silly-dragons-fix.md
packages/mui/src/components/MuiThemeProvider/theme.ts

Mui made some changes to the backdrop styling causing us to loose our transparancy.
| Light | Dark |
|---|---|
| <img width="531" alt="image" src="https://user-images.githubusercontent.com/648527/201626584-94b36c1b-cf3f-490a-8ffc-a8a94f04458e.png"> | <img width="531" alt="image" src="https://user-images.githubusercontent.com/648527/201626688-a1795884-590d-4a4a-b395-4ed1a1962632.png"> |

Fix backdrop color in dark mode

---

.changeset/cool-frogs-marry.md
example-widget-mui/src/ThemePage/ThemePage.tsx
packages/mui/src/components/MuiThemeProvider/MuiThemeProvider.tsx
packages/mui/src/components/MuiThemeProvider/theme.ts

This improves layout of dialog that have the scroll mode "body" by reducing the margin to 8 pixel as we have for the other scroll mode.
I also included a small improvement for my previous PR.

Improve styling of dialogs in the scroll mode "body"

---

.changeset/polite-windows-grow.md
.changeset/purple-bees-flow.md
packages/api/api-report.md
packages/api/src/api/extras/roomMember.test.ts
packages/api/src/api/extras/roomMember.ts
packages/testing/api-report.md
packages/testing/src/api/mockWidgetApi.test.ts
packages/testing/src/api/mockWidgetApi.ts

Permit null values for the displayname and avatar_url fields in the `m.room.member` event

---

.changeset/gold-snails-attack.md
packages/mui/src/components/ElementAvatar/createAvatarUrl.ts

The URL class has different behavior in Node that it has in the browser, where it is unable to handle custom protocols. To avoid this issue we don't use it here.

Fix generated avatar URLs

---

.changeset/late-humans-shave.md
packages/api/api-report.md
packages/api/src/api/WidgetApiImpl.test.ts
packages/api/src/api/WidgetApiImpl.ts
packages/api/src/api/types.ts
packages/testing/src/api/mockWidgetApi.test.ts
packages/testing/src/api/mockWidgetApi.ts

Extend the widgetApi with the new upload function in MSC 4039

---

.changeset/sweet-jeans-smile.md
example-widget-mui/README.md
example-widget-mui/package.json
example-widget-mui/src/App/App.tsx
example-widget-mui/src/ImagePage/Image.tsx
example-widget-mui/src/ImagePage/ImageListView.tsx
example-widget-mui/src/ImagePage/ImagePage.test.tsx
example-widget-mui/src/ImagePage/ImagePage.tsx
example-widget-mui/src/ImagePage/index.ts
example-widget-mui/src/NavigationPage/NavigationPage.tsx
packages/api/api-report.api.md
packages/api/package.json
packages/api/src/api/WidgetApiImpl.ts
packages/api/src/api/types.ts
packages/mui/package.json
packages/react/package.json
packages/testing/package.json
packages/testing/src/api/mockWidgetApi.ts
yarn.lock

Implements usage of the `download_file` action of the Widget API.
See [MSC4039](https://github.com/matrix-org/matrix-spec-proposals/pull/4039) .
Also moves the `UploadImagePage` page to `ImagePage` since it now demos up- and download of content.
Needs https://github.com/matrix-org/matrix-react-sdk/pull/12931

Implement the download_file widget action

---

.changeset/famous-frogs-eat.md
packages/mui/src/components/MuiThemeProvider/theme.ts

The idea of this PR is to add these options globally to the theme, so Menues and Tooltips in an application embedding a widget (such as the neoboard react sdk) directly work properly when fullscreened.

add fullscreen options to baseTheme

---

example-widget-mui/src/ImagePage/Image.tsx

Images were overflowing in the image list. This sets the image list explicitly, so that they fit into their containers.
| Before | After |
| --- | --- |
| ![image-list-before](https://github.com/user-attachments/assets/b55d7929-a9dc-4190-88b6-2ef23b40360a) | ![image-list-after](https://github.com/user-attachments/assets/cef48e37-075d-4693-b37c-fd375a9e82b0) |
No changeset, because [we ignore the example widget ](https://github.com/nordeck/matrix-widget-toolkit/blob/main/.changeset/config.json#L9)

Fix example widget image list layout

---

.changeset/poor-carrots-yawn.md
packages/mui/README.md
packages/mui/src/components/ElementAvatar/getColor.test.ts
packages/mui/src/components/ElementAvatar/getColor.ts
packages/mui/src/components/MuiThemeProvider/theme.ts

Align widget green and red with Element green and red to Keep the look of Element and widgets in sync.

Align widget and Element colors

---

packages/testing/package.json

vitest should be a dev dependency
This causes renovate to show it in the prod group like here: https://github.com/nordeck/matrix-widget-toolkit/pull/841

Move vitest to dev dependencies

---

eslint.config.mjs

By that we avoid calls without namespace and translations not working in packages depending on the SDK.

Add ESLint rule to enforce the "widget-toolkit" translation namespace

---

.changeset/wet-coats-love.md
containers/widget-server/Dockerfile
containers/widget-server/README.md
containers/widget-server/files/default.conf
containers/widget-server/files/mimetypes.conf

Adds proper mimetype configuration for `.js`, `.mjs` and `.cjs` files in the `widget-server` container.

Adds proper mime type config for js, cjs and mjs files

---

.changeset/fresh-peaches-smell.md
.changeset/khaki-mayflies-notice.md
example-widget-mui/src/PowerLevelsPage/PowerLevelsPage.tsx
example-widget-mui/src/PowerLevelsPage/powerLevelsApi.test.ts
example-widget-mui/src/PowerLevelsPage/powerLevelsApi.ts
packages/api/api-report.api.md
packages/api/src/api/WidgetApiImpl.test.ts
packages/api/src/api/WidgetApiImpl.ts
packages/api/src/api/index.ts
packages/api/src/api/types.ts
packages/api/src/api/utils.ts
packages/testing/src/api/mockWidgetApi.ts

Before, it waited for the same event sent back over the Widget API. If the was not updated, there was no such event.
Now sendStateEvent returns the response of the Matrix Widget Api with the event ID, among other things.

Change WidgetApi.sendStateEvent to return the Matrix widget Api result.

---

.github/dco.yml

Disable DCO checks for members

---

.changeset/yellow-seas-attend.md
packages/mui/src/components/ElementAvatar/ElementAvatar.tsx

Fixes „React does not recognize the `colorHash` prop on a DOM element.“ messages.

Prevent the colorHash prop being leaked to the DOM

---

.changeset/cuddly-kings-exercise.md
example-widget-mui/src/App/App.tsx
packages/api/api-report.api.md
packages/api/src/api/index.ts
packages/api/src/api/registration.test.ts
packages/api/src/api/registration.ts
packages/api/src/api/types.ts
packages/mui/src/components/MuiWidgetApiProvider/MuiWidgetApiProvider.test.tsx
packages/react/README.md
packages/react/src/components/WidgetApiProvider/WidgetApiProvider.test.tsx
packages/react/src/components/WidgetApiProvider/WidgetApiProvider.tsx

When introducing the Device ID widget parameter, all already registered widgets would fail to load, requiring a manual re-registration by a room member with enough permissions.
This PR removes device id from the required parameters for widget registration and adds a way for the `WidgetApiProvider` component to specify which, if any, parameters it must require, such as the device id, thus maintaining backwards compatibility for widgets that do not require it.

Support for optionally required widget parameters

---

.changeset/hot-trains-drop.md
packages/api/src/api/WidgetApiImpl.ts

Disables the `update_state` API that is not currently supported to be able to read room state.

Disable the update_state API to resolve issues with reading room state

---

.changeset/dull-bees-wave.md
packages/api/src/api/extras/events.test.ts
packages/api/src/api/extras/events.ts

We have introduced events validations in https://github.com/nordeck/matrix-widget-toolkit/pull/913. 
However, the toolkit could also receive stripped state events. These events are used by widgets and are currently filtered out.
This PR basically restores the previous behavior and allows to have `event_id`, `origin_server_ts` as `undefined` for the state events when the event is stripped.
Types are not changed in this PR.

Update validations to accept stripped state events

---

.github/renovate.json5

We overlooked some automerge config, causing PRs such as https://github.com/nordeck/matrix-widget-toolkit/pull/956.

Let Renovate automerge digest and pinDigest

---

.github/renovate.json5

Before:
After:
(disclaimer: "After" also is 2 weeks later worth of updates)

Make renovate group pins

---

.changeset/tame-trains-look.md
packages/api/api-report.api.md
packages/api/src/api/extras/index.ts
packages/api/src/api/extras/powerLevel.ts

Export additional functions so we can reuse them in widgets
